version: "3"
services:
  docker_dev_container_linux:
      container_name: ${cont_name:-dev_cont}
      privileged: true
      build:
        context: .
        dockerfile: dev_container.dockerfile
        args:
          uid: $uid
          gid: $gid
          uname: $uname
          docker_guid: 989
          progress: plain
      image: $image_name
      network_mode: host
      volumes:
        - $HOME/Project:$HOME/Project
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
        - /tmp/.X11-unix:/tmp/.X11-unix
      environment:
        - DISPLAY=$DISPLAY
        - XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR
      tty: true
      stdin_open: true